"""
Chart Saving Examples for fin_lib

This module demonstrates how to save charts generated by fin_lib analysis functions
to files for later use or reporting purposes.
"""

import fin_lib as fl
import os
from datetime import datetime
from pathlib import Path


def save_chart_to_file(chart, filename, chart_type="plotly"):
    """
    Save a chart to file with appropriate format.
    
    Args:
        chart: Chart object (Plotly Figure or Matplotlib Figure)
        filename: Output filename (without extension)
        chart_type: Type of chart ("plotly" or "matplotlib")
        
    Returns:
        String path to saved file
    """
    # Create charts directory if it doesn't exist
    charts_dir = Path("charts")
    charts_dir.mkdir(exist_ok=True)
    
    if chart_type == "plotly":
        # Save Plotly chart as HTML and PNG
        html_path = charts_dir / f"{filename}.html"
        png_path = charts_dir / f"{filename}.png"
        
        try:
            # Save as interactive HTML
            chart.write_html(str(html_path))
            print(f"✅ Saved interactive chart: {html_path}")
            
            # Try to save as PNG (requires kaleido)
            try:
                chart.write_image(str(png_path), width=1200, height=800)
                print(f"✅ Saved PNG chart: {png_path}")
                return str(png_path)
            except Exception as e:
                print(f"⚠️  Could not save PNG (install kaleido for PNG export): {e}")
                return str(html_path)
                
        except Exception as e:
            print(f"❌ Error saving Plotly chart: {e}")
            return None
            
    elif chart_type == "matplotlib":
        # Save Matplotlib chart as PNG
        png_path = charts_dir / f"{filename}.png"
        
        try:
            chart.savefig(str(png_path), dpi=300, bbox_inches='tight')
            print(f"✅ Saved matplotlib chart: {png_path}")
            return str(png_path)
        except Exception as e:
            print(f"❌ Error saving matplotlib chart: {e}")
            return None
    
    return None


def comprehensive_ttd_analysis_with_charts():
    """
    Comprehensive TTD analysis with all charts saved to files.
    
    Returns:
        Dictionary with analysis results and saved chart paths
    """
    print("🔍 COMPREHENSIVE TTD ANALYSIS WITH CHART SAVING")
    print("=" * 60)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    saved_charts = []
    
    # 1. Stock Quote and Historical Data with Chart
    print("📊 Getting TTD historical data with chart...")
    historical = fl.get_historical_data("TTD", period="1y", include_chart=True)
    
    if "chart" in historical:
        chart_path = save_chart_to_file(
            historical["chart"], 
            f"TTD_historical_{timestamp}",
            "plotly"
        )
        if chart_path:
            saved_charts.append({"type": "historical", "path": chart_path})
    
    # 2. Technical Analysis with Charts
    print("📈 Performing technical analysis with charts...")
    
    # RSI with chart
    rsi = fl.calculate_rsi("TTD", include_chart=True)
    if "chart" in rsi:
        chart_path = save_chart_to_file(
            rsi["chart"],
            f"TTD_RSI_{timestamp}",
            "plotly"
        )
        if chart_path:
            saved_charts.append({"type": "rsi", "path": chart_path})
    
    # MACD with chart
    macd = fl.calculate_macd("TTD", include_chart=True)
    if "chart" in macd:
        chart_path = save_chart_to_file(
            macd["chart"],
            f"TTD_MACD_{timestamp}",
            "plotly"
        )
        if chart_path:
            saved_charts.append({"type": "macd", "path": chart_path})
    
    # Bollinger Bands with chart
    bbands = fl.calculate_bollinger_bands("TTD", include_chart=True)
    if "chart" in bbands:
        chart_path = save_chart_to_file(
            bbands["chart"],
            f"TTD_BollingerBands_{timestamp}",
            "plotly"
        )
        if chart_path:
            saved_charts.append({"type": "bollinger_bands", "path": chart_path})
    
    # 3. Alpha/Beta Analysis with Chart
    print("🧠 Computing alpha/beta with chart...")
    alpha_beta = fl.alpha_intelligence.calculate_alpha_beta(
        "TTD", 
        benchmark="^GSPC", 
        period="1y", 
        include_chart=True
    )
    
    if "chart" in alpha_beta:
        chart_path = save_chart_to_file(
            alpha_beta["chart"],
            f"TTD_AlphaBeta_{timestamp}",
            "plotly"
        )
        if chart_path:
            saved_charts.append({"type": "alpha_beta", "path": chart_path})
    
    # 4. Fundamental Analysis with Chart
    print("💰 Analyzing fundamentals with chart...")
    fundamentals = fl.get_fundamentals("TTD", include_chart=True)
    
    if "chart" in fundamentals:
        chart_path = save_chart_to_file(
            fundamentals["chart"],
            f"TTD_Fundamentals_{timestamp}",
            "plotly"
        )
        if chart_path:
            saved_charts.append({"type": "fundamentals", "path": chart_path})
    
    print(f"\n✅ TTD analysis complete! Saved {len(saved_charts)} charts.")
    
    return {
        "symbol": "TTD",
        "timestamp": timestamp,
        "analysis": {
            "historical": historical,
            "rsi": rsi,
            "macd": macd,
            "bollinger_bands": bbands,
            "alpha_beta": alpha_beta,
            "fundamentals": fundamentals
        },
        "saved_charts": saved_charts
    }


def ttd_vs_spx_comparison_with_charts():
    """
    TTD vs SPX comparison analysis with all charts saved.
    
    Returns:
        Dictionary with comparison results and saved chart paths
    """
    print("\n📊 TTD vs SPX COMPARISON WITH CHART SAVING")
    print("=" * 60)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    saved_charts = []
    
    # 1. Performance Comparison Chart
    print("📈 Creating performance comparison chart...")
    comparison = fl.compare_symbols(
        ["TTD", "^GSPC"],
        period="2y",
        normalize=True,
        include_chart=True
    )
    
    if "chart" in comparison:
        chart_path = save_chart_to_file(
            comparison["chart"],
            f"TTD_vs_SPX_Performance_{timestamp}",
            "plotly"
        )
        if chart_path:
            saved_charts.append({"type": "performance_comparison", "path": chart_path})
    
    # 2. Individual Technical Analysis Charts
    print("📊 Creating individual technical analysis charts...")
    
    # TTD Technical Analysis
    ttd_technical = fl.technical_analysis(
        "TTD",
        indicators=["RSI", "MACD"],
        period="1y",
        include_chart=True
    )
    
    if "chart" in ttd_technical:
        chart_path = save_chart_to_file(
            ttd_technical["chart"],
            f"TTD_Technical_{timestamp}",
            "plotly"
        )
        if chart_path:
            saved_charts.append({"type": "ttd_technical", "path": chart_path})
    
    # SPX Technical Analysis
    spx_technical = fl.technical_analysis(
        "^GSPC",
        indicators=["RSI", "MACD"],
        period="1y",
        include_chart=True
    )
    
    if "chart" in spx_technical:
        chart_path = save_chart_to_file(
            spx_technical["chart"],
            f"SPX_Technical_{timestamp}",
            "plotly"
        )
        if chart_path:
            saved_charts.append({"type": "spx_technical", "path": chart_path})
    
    # 3. Alpha/Beta Analysis Chart
    print("🧠 Creating alpha/beta analysis chart...")
    alpha_beta = fl.alpha_intelligence.calculate_alpha_beta(
        "TTD",
        benchmark="^GSPC",
        period="2y",
        include_chart=True
    )
    
    if "chart" in alpha_beta:
        chart_path = save_chart_to_file(
            alpha_beta["chart"],
            f"TTD_AlphaBeta_vs_SPX_{timestamp}",
            "plotly"
        )
        if chart_path:
            saved_charts.append({"type": "alpha_beta_regression", "path": chart_path})
    
    print(f"\n✅ TTD vs SPX comparison complete! Saved {len(saved_charts)} charts.")
    
    return {
        "comparison": "TTD vs ^GSPC",
        "timestamp": timestamp,
        "analysis": {
            "performance_comparison": comparison,
            "ttd_technical": ttd_technical,
            "spx_technical": spx_technical,
            "alpha_beta": alpha_beta
        },
        "saved_charts": saved_charts
    }


def portfolio_optimization_with_charts():
    """
    Portfolio optimization analysis with correlation heatmap and other charts saved.
    
    Returns:
        Dictionary with portfolio results and saved chart paths
    """
    print("\n🎯 PORTFOLIO OPTIMIZATION WITH CHART SAVING")
    print("=" * 60)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    saved_charts = []
    symbols = ["TTD", "AAPL", "MSFT", "GOOGL", "TSLA"]
    
    # 1. Maximum Sharpe Ratio Portfolio
    print("🎯 Optimizing for maximum Sharpe ratio...")
    max_sharpe = fl.alpha_intelligence.portfolio_optimization(
        symbols,
        period="2y",
        method="max_sharpe",
        include_chart=True
    )
    
    if "chart" in max_sharpe:
        chart_path = save_chart_to_file(
            max_sharpe["chart"],
            f"Portfolio_MaxSharpe_Correlation_{timestamp}",
            "plotly"
        )
        if chart_path:
            saved_charts.append({"type": "max_sharpe_correlation", "path": chart_path})
    
    # 2. Minimum Volatility Portfolio
    print("🛡️ Optimizing for minimum volatility...")
    min_vol = fl.alpha_intelligence.portfolio_optimization(
        symbols,
        period="2y",
        method="min_vol",
        include_chart=True
    )
    
    if "chart" in min_vol:
        chart_path = save_chart_to_file(
            min_vol["chart"],
            f"Portfolio_MinVol_Correlation_{timestamp}",
            "plotly"
        )
        if chart_path:
            saved_charts.append({"type": "min_vol_correlation", "path": chart_path})
    
    # 3. Individual Stock Performance Charts
    print("📊 Creating individual stock performance charts...")
    for symbol in symbols:
        try:
            hist_data = fl.get_historical_data(symbol, period="1y", include_chart=True)
            if "chart" in hist_data:
                chart_path = save_chart_to_file(
                    hist_data["chart"],
                    f"{symbol}_Performance_{timestamp}",
                    "plotly"
                )
                if chart_path:
                    saved_charts.append({"type": f"{symbol}_performance", "path": chart_path})
        except Exception as e:
            print(f"⚠️  Could not create chart for {symbol}: {e}")
    
    print(f"\n✅ Portfolio optimization complete! Saved {len(saved_charts)} charts.")
    
    return {
        "symbols": symbols,
        "timestamp": timestamp,
        "analysis": {
            "max_sharpe": max_sharpe,
            "min_volatility": min_vol
        },
        "saved_charts": saved_charts
    }


def multi_asset_overview_with_charts():
    """
    Multi-asset market overview with all charts saved.
    
    Returns:
        Dictionary with market overview and saved chart paths
    """
    print("\n🌍 MULTI-ASSET MARKET OVERVIEW WITH CHART SAVING")
    print("=" * 60)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    saved_charts = []
    
    # 1. Forex Charts
    print("💱 Creating forex charts...")
    try:
        major_pairs = fl.forex.get_major_pairs(include_chart=True)
        if "chart" in major_pairs:
            chart_path = save_chart_to_file(
                major_pairs["chart"],
                f"Forex_MajorPairs_{timestamp}",
                "plotly"
            )
            if chart_path:
                saved_charts.append({"type": "forex_major_pairs", "path": chart_path})
        
        usd_eur = fl.forex.get_exchange_rate("USD", "EUR", include_chart=True)
        if "chart" in usd_eur:
            chart_path = save_chart_to_file(
                usd_eur["chart"],
                f"USD_EUR_Rate_{timestamp}",
                "plotly"
            )
            if chart_path:
                saved_charts.append({"type": "usd_eur_rate", "path": chart_path})
    except Exception as e:
        print(f"⚠️  Error creating forex charts: {e}")
    
    # 2. Cryptocurrency Charts
    print("₿ Creating cryptocurrency charts...")
    try:
        major_cryptos = fl.crypto.get_major_cryptos(include_chart=True)
        if "chart" in major_cryptos:
            chart_path = save_chart_to_file(
                major_cryptos["chart"],
                f"Crypto_MajorCoins_{timestamp}",
                "plotly"
            )
            if chart_path:
                saved_charts.append({"type": "crypto_major", "path": chart_path})
        
        btc_price = fl.crypto.get_crypto_price("BTC-USD", include_chart=True)
        if "chart" in btc_price:
            chart_path = save_chart_to_file(
                btc_price["chart"],
                f"BTC_USD_Price_{timestamp}",
                "plotly"
            )
            if chart_path:
                saved_charts.append({"type": "btc_price", "path": chart_path})
    except Exception as e:
        print(f"⚠️  Error creating crypto charts: {e}")
    
    # 3. Commodities Charts
    print("🥇 Creating commodities charts...")
    try:
        precious_metals = fl.commodities.get_precious_metals(include_chart=True)
        if "chart" in precious_metals:
            chart_path = save_chart_to_file(
                precious_metals["chart"],
                f"Commodities_PreciousMetals_{timestamp}",
                "plotly"
            )
            if chart_path:
                saved_charts.append({"type": "precious_metals", "path": chart_path})
        
        gold_price = fl.commodities.get_commodity_price("GC=F", include_chart=True)
        if "chart" in gold_price:
            chart_path = save_chart_to_file(
                gold_price["chart"],
                f"Gold_Price_{timestamp}",
                "plotly"
            )
            if chart_path:
                saved_charts.append({"type": "gold_price", "path": chart_path})
    except Exception as e:
        print(f"⚠️  Error creating commodities charts: {e}")
    
    # 4. Economic Indicators Charts
    print("📊 Creating economic indicators charts...")
    try:
        treasury_rates = fl.economics.get_treasury_rates(include_chart=True)
        if "chart" in treasury_rates:
            chart_path = save_chart_to_file(
                treasury_rates["chart"],
                f"Treasury_Rates_{timestamp}",
                "plotly"
            )
            if chart_path:
                saved_charts.append({"type": "treasury_rates", "path": chart_path})
        
        market_sentiment = fl.economics.get_market_sentiment(include_chart=True)
        if "chart" in market_sentiment:
            chart_path = save_chart_to_file(
                market_sentiment["chart"],
                f"Market_Sentiment_{timestamp}",
                "plotly"
            )
            if chart_path:
                saved_charts.append({"type": "market_sentiment", "path": chart_path})
    except Exception as e:
        print(f"⚠️  Error creating economic charts: {e}")
    
    print(f"\n✅ Multi-asset overview complete! Saved {len(saved_charts)} charts.")
    
    return {
        "timestamp": timestamp,
        "saved_charts": saved_charts
    }


def run_all_chart_saving_examples():
    """
    Run all chart saving examples and return summary.
    
    Returns:
        Dictionary with all results and chart paths
    """
    print("🚀 RUNNING ALL CHART SAVING EXAMPLES")
    print("=" * 70)
    
    all_results = {
        "execution_timestamp": datetime.now().isoformat(),
        "examples": {},
        "total_charts_saved": 0
    }
    
    try:
        # 1. Comprehensive TTD Analysis
        ttd_results = comprehensive_ttd_analysis_with_charts()
        all_results["examples"]["ttd_comprehensive"] = ttd_results
        all_results["total_charts_saved"] += len(ttd_results["saved_charts"])
        
        # 2. TTD vs SPX Comparison
        comparison_results = ttd_vs_spx_comparison_with_charts()
        all_results["examples"]["ttd_vs_spx"] = comparison_results
        all_results["total_charts_saved"] += len(comparison_results["saved_charts"])
        
        # 3. Portfolio Optimization
        portfolio_results = portfolio_optimization_with_charts()
        all_results["examples"]["portfolio_optimization"] = portfolio_results
        all_results["total_charts_saved"] += len(portfolio_results["saved_charts"])
        
        # 4. Multi-Asset Overview
        multi_asset_results = multi_asset_overview_with_charts()
        all_results["examples"]["multi_asset_overview"] = multi_asset_results
        all_results["total_charts_saved"] += len(multi_asset_results["saved_charts"])
        
        print(f"\n🎉 ALL CHART SAVING EXAMPLES COMPLETED!")
        print(f"📊 Total charts saved: {all_results['total_charts_saved']}")
        print(f"📁 Charts saved in: ./charts/ directory")
        print("=" * 70)
        
    except Exception as e:
        print(f"\n❌ Error during execution: {str(e)}")
        all_results["error"] = str(e)
        import traceback
        traceback.print_exc()
    
    return all_results


if __name__ == "__main__":
    """
    Example usage of chart saving functions.
    """
    print("fin_lib Chart Saving Examples")
    print("Using TTD (The Trade Desk) and SPX (S&P 500) tickers")
    print("=" * 70)
    
    # Install kaleido for PNG export (optional)
    print("💡 Tip: Install 'kaleido' for PNG chart export:")
    print("   pip install kaleido")
    print()
    
    # Run all examples
    results = run_all_chart_saving_examples()
    
    print("\n📋 SUMMARY:")
    print(f"Charts saved: {results.get('total_charts_saved', 0)}")
    print("Check the 'charts/' directory for all saved visualizations!")
