from kratos.subagents.registry import SubAgentSpec, ToolBinding, register_subagent
from kratos.subagents.system_prompts import SYSTEM_PROMPTS


@register_subagent
def technicals_spec() -> SubAgentSpec:
    prompt_def = SYSTEM_PROMPTS["technical_indicators"]
    return SubAgentSpec(
        name="technical_indicators",
        description="Comprehensive technical analysis indicators including moving averages, oscillators, momentum, volatility, and volume indicators",
        prompt=prompt_def["prompt"],
        output_format=prompt_def["output_format"],
        tools=[
            ToolBinding("SMA", "Simple moving average (SMA) values"),
            ToolBinding("EMA", "Exponential moving average (EMA) values"),
            ToolBinding("WMA", "Weighted moving average (WMA) values"),
            ToolBinding("DEMA", "Double exponential moving average (DEMA) values"),
            ToolBinding("TEMA", "Triple exponential moving average (TEMA) values"),
            ToolBinding("TRIMA", "Triangular moving average (TRIMA) values"),
            ToolBinding("KAMA", "Kaufman adaptive moving average (KAMA) values"),
            ToolBinding("MAMA", "MESA adaptive moving average (MAMA) values"),
            ToolBinding("VWAP", "Volume weighted average price (VWAP) for intraday time series"),
            ToolBinding("T3", "Triple exponential moving average (T3) values"),
            ToolBinding("MACD", "Moving average convergence / divergence (MACD) values"),
            ToolBinding("MACDEXT", "Moving average convergence / divergence values with controllable moving average type"),
            ToolBinding("STOCH", "Stochastic oscillator (STOCH) values"),
            ToolBinding("STOCHF", "Stochastic fast (STOCHF) values"),
            ToolBinding("RSI", "Relative strength index (RSI) values"),
            ToolBinding("STOCHRSI", "Stochastic relative strength index (STOCHRSI) values"),
            ToolBinding("WILLR", "Williams' %R (WILLR) values"),
            ToolBinding("ADX", "Average directional movement index (ADX) values"),
            ToolBinding("ADXR", "Average directional movement index rating (ADXR) values"),
            ToolBinding("APO", "Absolute price oscillator (APO) values"),
            ToolBinding("PPO", "Percentage price oscillator (PPO) values"),
            ToolBinding("MOM", "Momentum (MOM) values"),
            ToolBinding("BOP", "Balance of power (BOP) values"),
            ToolBinding("CCI", "Commodity channel index (CCI) values"),
            ToolBinding("CMO", "Chande momentum oscillator (CMO) values"),
            ToolBinding("ROC", "Rate of change (ROC) values"),
            ToolBinding("ROCR", "Rate of change ratio (ROCR) values"),
            ToolBinding("AROON", "Aroon (AROON) values"),
            ToolBinding("AROONOSC", "Aroon oscillator (AROONOSC) values"),
            ToolBinding("MFI", "Money flow index (MFI) values"),
            ToolBinding("TRIX", "1-day rate of change of a triple smooth exponential moving average (TRIX) values"),
            ToolBinding("ULTOSC", "Ultimate oscillator (ULTOSC) values"),
            ToolBinding("DX", "Directional movement index (DX) values"),
            ToolBinding("MINUS_DI", "Minus directional indicator (MINUS_DI) values"),
            ToolBinding("PLUS_DI", "Plus directional indicator (PLUS_DI) values"),
            ToolBinding("MINUS_DM", "Minus directional movement (MINUS_DM) values"),
            ToolBinding("PLUS_DM", "Plus directional movement (PLUS_DM) values"),
            ToolBinding("BBANDS", "Bollinger bands (BBANDS) values"),
            ToolBinding("MIDPOINT", "Midpoint values - (highest value + lowest value)/2"),
            ToolBinding("MIDPRICE", "Midpoint price values - (highest high + lowest low)/2"),
            ToolBinding("SAR", "Parabolic SAR (SAR) values"),
            ToolBinding("TRANGE", "True range (TRANGE) values"),
            ToolBinding("ATR", "Average true range (ATR) values"),
            ToolBinding("NATR", "Normalized average true range (NATR) values"),
            ToolBinding("AD", "Chaikin A/D line (AD) values"),
            ToolBinding("ADOSC", "Chaikin A/D oscillator (ADOSC) values"),
            ToolBinding("OBV", "On balance volume (OBV) values"),
            ToolBinding("HT_TRENDLINE", "Hilbert transform, instantaneous trendline (HT_TRENDLINE) values"),
            ToolBinding("HT_SINE", "Hilbert transform, sine wave (HT_SINE) values"),
            ToolBinding("HT_TRENDMODE", "Hilbert transform, trend vs cycle mode (HT_TRENDMODE) values"),
            ToolBinding("HT_DCPERIOD", "Hilbert transform, dominant cycle period (HT_DCPERIOD) values"),
            ToolBinding("HT_DCPHASE", "Hilbert transform, dominant cycle phase (HT_DCPHASE) values"),
            ToolBinding("HT_PHASOR", "Hilbert transform, phasor components (HT_PHASOR) values"),
        ],
        group="technical",
    )
